//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::Language;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Packs_translations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pack_id: i32,
    pub language: Language,
    pub title: String,
    pub short_description: String,
    #[sea_orm(column_type = "Text")]
    pub full_description: String,
    pub features: Option<Vec<String>>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::packs::Entity",
        from = "Column::PackId",
        to = "super::packs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Packs,
}

impl Related<super::packs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Packs.def()
    }
}
