//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::images::Entity as Images;
pub use super::packs::Entity as Packs;
pub use super::training_models::Entity as TrainingModels;
pub use super::transactions::Entity as Transactions;
pub use super::user_credits::Entity as UserCredits;
pub use super::users::Entity as Users;
