//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::AspectRatio;
use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Videos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub user_id: i32,
    #[sea_orm(column_type = "Text")]
    pub user_prompt: String,
    #[sea_orm(column_type = "Text")]
    pub sys_prompt: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub negative_prompt: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub alt: String,
    pub duration: i32,
    pub enhance_prompt: bool,
    pub generate_audio: bool,
    pub seed: Option<i32>,
    pub status: Status,
    pub aspect_ratio: AspectRatio,
    pub video_cost: i32,
    pub fal_ai_request_id: Option<String>,
    pub is_favorite: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub video_s3_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub video_url_fal: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub thumbnail_s3_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
